-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ECOMM_STORE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ECOMM_STORE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ECOMM_STORE` DEFAULT CHARACTER SET utf8 ;
USE `ECOMM_STORE` ;

-- -----------------------------------------------------
-- Table `ECOMM_STORE`.`CUSTOMERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECOMM_STORE`.`CUSTOMERS` (
  `CUSTOMER_ID` INT UNSIGNED NOT NULL,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST_NAME` VARCHAR(100) NOT NULL,
  `ADDRESS` VARCHAR(45) NOT NULL,
  `CITY` VARCHAR(45) NOT NULL,
  `STATE` VARCHAR(45) NOT NULL,
  `COUNTRY` VARCHAR(45) NOT NULL,
  `ZIPCODE` VARCHAR(45) NOT NULL,
  `PHONE_NUMBER` INT(10) NOT NULL,
  `EMAIL_ID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`CUSTOMER_ID`),
  UNIQUE INDEX `CUSTOMER_ID_UNIQUE` (`CUSTOMER_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECOMM_STORE`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECOMM_STORE`.`PRODUCTS` (
  `PRODUCT_ID` INT UNSIGNED NOT NULL,
  `NAME` VARCHAR(100) NOT NULL,
  `TYPE` VARCHAR(100) NOT NULL,
  `PRICE` FLOAT NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`PRODUCT_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECOMM_STORE`.`PAYMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECOMM_STORE`.`PAYMENTS` (
  `PAYMENT_ID` INT UNSIGNED NOT NULL,
  `CUSTOMER_ID` INT UNSIGNED NOT NULL,
  `TYPE` VARCHAR(45) NOT NULL,
  `CC_NUMBER` CHAR(16) NOT NULL,
  `EXPIRATION_DATE` DATE NOT NULL,
  `CVV` CHAR(3) NOT NULL,
  `EMAIL_ID` VARCHAR(45) NULL,
  PRIMARY KEY (`PAYMENT_ID`),
  UNIQUE INDEX `PAYMENT_ID_UNIQUE` (`PAYMENT_ID` ASC) VISIBLE,
  CONSTRAINT `PAYMENTS_CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `ECOMM_STORE`.`CUSTOMERS` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ECOMM_STORE`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ECOMM_STORE`.`ORDERS` (
  `ORDER_ID` INT UNSIGNED NOT NULL,
  `DEVICE` VARCHAR(45) NOT NULL,
  `PRODUCT_ID` INT UNSIGNED NOT NULL,
  `CUSTOMER_ID` INT UNSIGNED NOT NULL,
  `PAYMENT_ID` INT UNSIGNED NOT NULL,
  `SHIPPING_ADDRESS` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ORDER_ID`),
  UNIQUE INDEX `ORDER_ID_UNIQUE` (`ORDER_ID` ASC) VISIBLE,
  INDEX `PRODUCT_ID_idx` (`PRODUCT_ID` ASC) VISIBLE,
  INDEX `CUSTOMER_ID_idx` (`CUSTOMER_ID` ASC) VISIBLE,
  INDEX `PAYMENT_ID_idx` (`PAYMENT_ID` ASC) VISIBLE,
  CONSTRAINT `PRODUCT_ID`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `ECOMM_STORE`.`PRODUCTS` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORDERS_CUSTOMER_ID`
    FOREIGN KEY (`CUSTOMER_ID`)
    REFERENCES `ECOMM_STORE`.`CUSTOMERS` (`CUSTOMER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PAYMENT_ID`
    FOREIGN KEY (`PAYMENT_ID`)
    REFERENCES `ECOMM_STORE`.`PAYMENTS` (`PAYMENT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
